#The shiny codes generated by the function2shiny is not completely automatic 
#and you need to do some manual trim, e.g. add new libraries if needed, 
#edit ui part to better display the inputs, 
#edit output, add codes for enable/disable input, etc.
library(shiny)
library(shinyjs)
######### UI part #######  
ui<-fluidPage( 
  shinyjs::useShinyjs(),
  titlePanel('Average duration of treatment estimate'),
  sidebarLayout( sidebarPanel( 
    
    div(class='well', h4('Input information'), 
        numericInput('Median.TR',label ='Median PFS' , value =18),
        numericInput('increase.rate',label ='Increase rate of drug use per year' , value =0.03)
    )),
    mainPanel( 
      h3(''),
      htmlOutput('txt.s'),
      h3(''),
      tableOutput('summary'),
      hr(),
      htmlOutput('txt.plot'),
      plotOutput('plot')
    )))
######## Server part #########
server<-function(input,output,session){
  width<-800
  height<-400
  
  ret<-reactive({
    Median.TR<-input$Median.TR
    increase.rate<-input$increase.rate
    m1 <- Median.TR/log(2)
    samplesize.y1 <- 1000
    years <- 10
    samplesize.y <- time.start <- NULL
    for (i in 1:years) {
      samplesize.y <- round(c(samplesize.y, samplesize.y1 * (1 + increase.rate)^(i - 1)), 0)
    }
    samplesize <- sum(samplesize.y)
    for (i in 1:years) {
      time.start <- c(time.start, seq((i - 1) * 12, i * 12, length.out = samplesize.y[i]))
    }
    data <- data.frame(1:samplesize, time.start)
    data$meanS <- m1
    for (i in 1:samplesize) {
      data$y[i] <- rexp(1, rate = 1/data$meanS[i])
    }
    data$time.end <- data$time.start + data$y
    colnames(data) <- c("ID", "time.start", "meanS", "y", "time.end")
    subfunction <- function(start.month, period = 12) {
      data.timeframe <- data[(data$time.start <= start.month & data$time.end > start.month) | (data$time.start > start.month & data$time.start < (start.month + period)), ]
      datacut <- data.timeframe
      datacut$newstart <- ifelse(datacut$time.start < start.month, start.month, datacut$time.start)
      datacut$newend <- ifelse(datacut$time.end < (start.month + period), datacut$time.end, start.month + period)
      datacut$duration <- datacut$newend - datacut$newstart
      return(mean(datacut$duration))
    }
    sequence <- seq(0, 108, by = 12)
    average <- NULL
    for (i in sequence) {
      average <- round(c(average, subfunction(i)), 2)
    }
    outfile <- tempfile(fileext='.png')
    png(outfile,width = width,height = height)
    par(mfrow=c(1,2))
    #plot 1
    plot(average ~ c(1:10), type = "b",xlab="Time after drug on market (Year)",
         ylab="Average duration of treatment",
         main="Average duration of treatment per year")
    grid()
    #plot 2
    start.month<-36;period<-12
    data<-data[data$ID %in% ceiling(seq.int(1,nrow(data),length.out=100)),]
    data.timeframe<-data[(data$time.start<=start.month & data$time.end>start.month) | 
                           (data$time.start>start.month & data$time.start<(start.month+period)),]
    
    plot(c(data$time.start,data$time.end), rep(data$ID,2),type="n",ylab="Patient ID",xlab="Time after drug on market (Year)",
         main="Simulated individual patient data within the 4th year",xaxt="n")
    axis(1,at=seq(0,240,by=24),labels=seq(0,20,by=2))
    
    segments(data[,"time.start"], data[,"ID"], data[,"time.end"], data[,"ID"], col= 'lightgrey')
    segments(data.timeframe[,"time.start"], data.timeframe[,"ID"], data.timeframe[,"time.end"], data.timeframe[,"ID"], col= 'red')
    points(data[,"time.end"],data[,"ID"],pch=4,cex=0.5,col='lightgrey')
    points(data.timeframe[,"time.end"],data.timeframe[,"ID"],pch=4,cex=0.5)
    grid()
    abline(v=c(start.month,start.month+period))
    abline(v=120,col="grey")
    
    dev.off()
    table <- matrix(0, nrow = 2, ncol = 11)
    table[1, 2:11] <- 1:10
    table[2, 2:11] <- average
    table[, 1] <- c("Year", "Average duration of treatment (Month)")
    # print.matrix <- function(m){
    #   write.table(format(m),
    #               row.names=F, col.names=F, quote=F)
    # }
    # table<-print(table)
    list(table,outfile)
  })
  ############# OUTPUT ##########
  output$summary<-renderTable({
    ret()[[1]]
  },include.rownames=FALSE,include.colnames=FALSE)
  
  output$plot<-renderImage({
    
    list(src = ret()[[2]],
         contentType = 'image/png',
         width = width,
         height = height,
         alt = "")
  },deleteFile=TRUE)
  
  output$txt.s=renderText({"<b>Table: Average duration of treamtment (DoT) per year</b>"})
  output$txt.plot=renderText({"<b>The 1st plot</b> below shows the estimated average DoT per year after the drug is on market.
    <b>The 2nd plot</b> below shows how the average DoT is calculated per year. Take the 4th year as an example, we first simulate
    individual DoT within 10 years after drug on market (greyed lines); patients on treatment at anytime in the 4th year are marked in red. The average
    DoT is calculated as the average length of the red lines within the time frame, i.e. the 4th year"})
  }
shinyApp(ui=ui,server=server)
